//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatIfF1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ergast.com/api/f1/")]
        public string f1APIRoot {
            get {
                return ((string)(this["f1APIRoot"]));
            }
            set {
                this["f1APIRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int playbackFramerate {
            get {
                return ((int)(this["playbackFramerate"]));
            }
            set {
                this["playbackFramerate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double playbackSpeed {
            get {
                return ((double)(this["playbackSpeed"]));
            }
            set {
                this["playbackSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Mgo+DSMBaFt/QHRqVVhjVFpFdEBBXHxAd1p/VWJYdVt5flBPcDwsT3RfQF5jSH9Vd01iX3xYeX1QQA==;Mgo+DSMBPh8sVXJ0S0J+XE9HflRDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS31Td0RlWHdfdndSRmFYVw==;ORg4AjUWIQA/Gnt2VVhkQlFadVdJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxQdkRiX35WcXJWQWBfVUI=;OTUwNDYzQDMyMzAyZTM0MmUzMGRqYVZoeElvQlF4VDgwNjREK1E3V0J0ZnFnNU5lWjRlNnBUdkZrYXJZRDg9;OTUwNDY0QDMyMzAyZTM0MmUzMGlCLzRRTThZeExZWjREbnNRWUp0Z09YSWRWOFdpelFiY2huNG1oL1IybXc9;NRAiBiAaIQQuGjN/V0Z+WE9EaFxKVmJLYVB3WmpQdldgdVRMZVVbQX9PIiBoS35RdUViWHlfeHVTRWddUEFw;OTUwNDY2QDMyMzAyZTM0MmUzMGVJaG1YRThkZ21UdEhBcUo1NjJtNWM1NU9ZdUdUQmJWUG5yV0pxZHhiajg9;OTUwNDY3QDMyMzAyZTM0MmUzMGl0S1NGUmxTeE1WMU9SWkp0OWFWWXFyZEtXenRORmYwYnlJb1pGT3hVajg9;Mgo+DSMBMAY9C3t2VVhkQlFadVdJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxQdkRiX35WcXJWQWFVV0I=;OTUwNDY5QDMyMzAyZTM0MmUzMEFzem5acXd2bUQxaHhHb0ZXdjhpZEErY1NCdXQ0L3RFMWt0ZThqdFdRekU9;OTUwNDcwQDMyMzAyZTM0MmUzMG1aSWg2aU53UEpYSTJISCtKQUtla01JVXRHTlZoOFRjdFgxOUpPci9IakU9;OTUwNDcxQDMyMzAyZTM0MmUzMGVJaG1YRThkZ21UdEhBcUo1NjJtNWM1NU9ZdUdUQmJWUG5yV0pxZHhiajg9")]
        public string syncfusionLicenseKey {
            get {
                return ((string)(this["syncfusionLicenseKey"]));
            }
            set {
                this["syncfusionLicenseKey"] = value;
            }
        }
    }
}
